Add a prefer wayland option
Quaver/MonoGame pull request #7
Opened 2020-06-12 08:25 UTC by YaLTeR

2020-06-13 13:21 UTC, Swan requested changes

2020-06-13 13:21 UTC, Swan commented on MonoGame.Framework/Game.cs
> +        // If set to true, try to initialize the Wayland SDL video platform first.
```suggestion
        /// <summary>
        ///     If set to true, try to initialize the Wayland SDL video platform first.
        /// </summary>
```

2020-06-13 13:21 UTC, Swan commented on MonoGame.Framework/Game.cs
> +        public Game(bool preferWayland)
Should probably make this argument optional

```suggestion
        public Game(bool preferWayland = false)
```

2020-06-15 18:02 UTC, merged

2020-07-13 04:21 UTC, lurr commented
Would it be better to instead check the `XDG_SESSION_TYPE` environment variable here instead? This would remove the requirement for this argument and allow smarter selection of which SDL video subsystem to initialize.

2020-07-13 04:53 UTC, YaLTeR commented
From what I recall, this isn't a standard environment variable. In any case, I'd rather simply make this the default behavior, but I'm waiting for SDL2 to implement CSD.